import type { ProviderFlow } from "./index";

export const googleFlow = {
  id: "google",
  label: "Google Gemini",
  auth: "api-key",
  authMethods: ["api-key"],
  defaultAuthMethod: "api-key",
  apiEnvVar: "GEMINI_API_KEY",
  secretSources: ["shared-storage", "direct-config", "external-env"],
  defaultApi: "google-generative-ai",
  defaultBaseUrl: "https://generativelanguage.googleapis.com",
  knownModels: [
    {
      id: "gemini-2.5-pro",
      label: "Gemini 2.5 Pro",
      api: "google-generative-ai",
      reasoning: true,
      input: ["text", "image"],
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
      contextWindow: 1048576,
      maxTokens: 65536,
    },
    {
      id: "gemini-2.5-flash",
      label: "Gemini 2.5 Flash",
      api: "google-generative-ai",
      reasoning: false,
      input: ["text", "image"],
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
      contextWindow: 1048576,
      maxTokens: 65536,
    },
    {
      id: "gemini-2.0-flash",
      label: "Gemini 2.0 Flash",
      api: "google-generative-ai",
      reasoning: false,
      input: ["text", "image"],
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
      contextWindow: 1048576,
      maxTokens: 8192,
    },
    {
      id: "gemini-2.0-pro",
      label: "Gemini 2.0 Pro",
      api: "google-generative-ai",
      reasoning: true,
      input: ["text", "image"],
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
      contextWindow: 1048576,
      maxTokens: 65536,
    },
    {
      id: "gemini-1.5-pro",
      label: "Gemini 1.5 Pro",
      api: "google-generative-ai",
      reasoning: false,
      input: ["text", "image"],
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
      contextWindow: 2097152,
      maxTokens: 8192,
    },
  ],
  defaultModelSuggestions: [
    { alias: "default", modelId: "gemini-2.0-flash", label: "Gemini 2.0 Flash" },
    { alias: "reasoning", modelId: "gemini-2.0-pro", label: "Gemini 2.0 Pro" },
  ],
} satisfies ProviderFlow;
