import type { ProviderFlow } from "./index";

export const openaiFlow = {
  id: "openai",
  label: "OpenAI",
  auth: "api-key",
  authMethods: ["api-key"],
  defaultAuthMethod: "api-key",
  apiEnvVar: "OPENAI_API_KEY",
  secretSources: ["shared-storage", "direct-config", "external-env"],
  defaultBaseUrl: "https://api.openai.com/v1",
  knownModels: [
    {
      id: "gpt-4o",
      label: "GPT-4o",
      api: "openai-responses",
      reasoning: false,
      input: ["text", "image"],
      contextWindow: 128000,
      maxTokens: 16384,
    },
    {
      id: "gpt-4o-mini",
      label: "GPT-4o Mini",
      api: "openai-responses",
      reasoning: false,
      input: ["text", "image"],
      contextWindow: 128000,
      maxTokens: 16384,
    },
    {
      id: "gpt-4.1",
      label: "GPT-4.1",
      api: "openai-responses",
      reasoning: false,
      input: ["text", "image"],
      contextWindow: 1047576,
      maxTokens: 32768,
    },
    {
      id: "gpt-4.1-mini",
      label: "GPT-4.1 Mini",
      api: "openai-responses",
      reasoning: false,
      input: ["text", "image"],
      contextWindow: 1047576,
      maxTokens: 32768,
    },
    {
      id: "o3",
      label: "OpenAI o3",
      api: "openai-responses",
      reasoning: true,
      input: ["text", "image"],
      contextWindow: 200000,
      maxTokens: 100000,
    },
    {
      id: "o4-mini",
      label: "OpenAI o4-mini",
      api: "openai-responses",
      reasoning: true,
      input: ["text", "image"],
      contextWindow: 200000,
      maxTokens: 100000,
    },
  ],
  defaultModelSuggestions: [
    { alias: "default", modelId: "gpt-4o", label: "GPT-4o" },
    { alias: "fast", modelId: "gpt-4o-mini", label: "GPT-4o Mini" },
  ],
} satisfies ProviderFlow;
